### ISSUE TITLE
Issue with Wait-AnsibleJob

### ISSUE THREAD

**Issue by weiyentan** [gpduck/AnsibleTower-PowerShell#14]
The time function  in wait-ansiblejob  is tied to utc. This has issues when the host (where the containers are installed on) are another  Region

**Comment by gpduck** [comment]
I don't see where the job time is being used, but I did find a bug calculating the remaining time before the timeout occurs.  Can you test the latest build from AppVeyor to see if this fixes your issue?

https://ci.appveyor.com/project/gpduck/ansibletower-powershell/builds/23296331/job/jk86j1dl5cf4fi8e/artifacts
