### ISSUE TITLE
Get-AnsibleJobTemplate function limited to 25 results

### ISSUE THREAD

**Issue by Chris-Carmichael** [gpduck/AnsibleTower-PowerShell#2]
Hey Trond,

We have like 100 or so job templates on a baby AWX deployment.  Everything works great except for Get-AnsibleJobTemplate.  When I run it by itself, it only returns 25 results:

```
PS C:\Users\carmi> $templates = Get-AnsibleJobTemplate
PS C:\Users\carmi> $templates.count
25
```

I dug through the code and API documentation but nothing is popping out.  Wondering if you've seen this or if I'm doing something dumb.

**Comment by trondhindenes** [comment]
Hi, thanks for reporting this! I'm assuming AWX does some paging in its api. I'm afraid I haven't looked at this code in a very long time, but it should be reasonable straight-forward to understand. I'm swamped for time at the moment so I can't promise to look at this in the near future.

**Comment by trondhindenes** [comment]
I would put a breakpoint around here: https://github.com/trondhindenes/AnsibleTower-PowerShell/blob/master/AnsibleTower.psm1#L129 and see what you get back. The Django rest framework that Ansible uses likely has paging builtin, so the json result should contain a "nextlink" or something that can be looped over to get the full result.

**Comment by Chris-Carmichael** [comment]
Hey Trond, I fixed it already.  You were right...AWX pages through the job templates so I just shuffled through the Next property until I got everything.

I need to do a pull request probably.  Just been crazy at work.

**Comment by weiyentan** [comment]
Hi Chris. I was reading through this. I was wondering whether this has been merged? I am going to be using awx and would love to have the fix that you have written. :)

**Comment by gpduck** [comment]
This should be fixed in the latest pre-release builds that are up on the gallery.  Can someone verify this for me (we only have 8 templates so far and I haven't written New-AnsibleJobTemplate yet)

**Comment by Chris-Carmichael** [comment]
Closing this issue.

```
[9]: $jobtemplates = Get-AnsibleJobTemplate

[10]: $jobtemplates.count
245
```
