### ISSUE TITLE
Update for API v2

### ISSUE THREAD

**Issue by ErykVoelkerKodiak** [gpduck/AnsibleTower-PowerShell#25]
It looks like the module is only compatible with AWX/Ansible-Tower running API v1. Is there or can there be an up date for API v2?

**Comment by weiyentan** [comment]
The new version does. I inspected the code and saw it says v2

**Comment by ErykVoelkerKodiak** [comment]
Thank you for your response.

I'm not able to use the 'Connect-AnsibleTower' using the version available in the PowerShell gallery. The GitHub source does have the update for API v2 so I'll download the source from GitHub.

Are there plans to update the PowerShell gallery with the API v2 version?

**Comment by weiyentan** [comment]
Use preview option in the gallery. Its there
